src/Entity/Tuto.php
<?php

namespace App\Entity;

use App\Repository\TutoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TutoRepository::class)]
class Tuto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Auteur = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $images = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): static
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(string $images): static
    {
        $this->images = $images;

        return $this;
    }

    
}

src/Form/TutoType.php
<?php

namespace App\Form;

use App\Entity\Tuto;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;


class TutoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('Auteur', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('images', FileType::class, [
                'label' => 'Tuto (Image File)',
                'mapped' => false,
                'required' => true,
                
            ])
        ;
         
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tuto::class,
        ]);
    }
}

src/Controller/TutoController.php
<?php

namespace App\Controller;

use App\Entity\Tuto;
use App\Form\TutoType;
use App\Repository\TutoRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\SluggerInterface;

#[IsGranted('ROLE_USER')]
class TutoController extends AbstractController
{
    
    
    #[Route('/tuto/list', name: 'tuto_list')]
    public function show(TutoRepository $tutoRepository): Response 
    {
        return $this->render('tuto/index.html.twig', [
            'tutos' => $tutoRepository->findAll(),
        ]);
    }


    #[Route('/tuto/{id}', name: 'tuto_show')]
    public function showbyid(TutoRepository $tutoRepository, int $id): Response
    {   
        
        $tuto  =$tutoRepository->find($id);
        if (!$tuto) {
            throw $this->createNotFoundException(
                'No tuto found for id '.$id
            );
        }

        return $this->render('tuto/showbyid.html.twig', [
            'tuto' => $tuto,
        ]);
    }


}

templates/tuto/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tuto{% endblock %}

{% block body %}

    {% include 'partials/navbar.html.twig' %}

    <div class="container">
        <div class="row">
        {% for tuto in tutos %}
            <div class="col-md-4">
                <div class="card mb-4 mt-2 custom-card">
                    <img src="{{ asset('uploads/tuto/' ~ tuto.images) }}" class="img-fluid img-thumbnail" alt="Tuto Image">
                    <div class="card-body">
                        <h5 class="card-title">{{ tuto.titre }}</h5>
                        <p class="card-text"><small class="text-muted">By {{ tuto.auteur }}</small></p>
                    </div>
                    <div class="card-footer">
                        {# <button class="btn btn-sm btn-primary btnseedetails" >Voir Details</button> #}
                        <a href="{{ path('tuto_show', {'id': tuto.id})}}" class="btn btn-sm btn-primary btnseedetails" type="button">Voir details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

templates/tuto/showbyid.html.twig
{% extends "base.html.twig" %}

{% block title %}Show tuto{% endblock %}

{% block body %}
    {% include 'partials/navbar.html.twig' %}
    {{ tuto.titre}}

{% endblock %}